language: node_js # 设置语言
node_js: 12 # 设置相应版本
install:
    - npm install # 安装hexo及插件
script:
    - hexo clean # 清除
    - hexo g # 生成
after_script:
    - cd ./public
    - git init
    - git config user.name "ingjieye"
    - git config user.email "ingjieye@gmail.com"
    - git add .
    - git commit -m "Travis CI Auto Builder"
    - git push --force --quiet "https://${Travis_Token}@${GH_REF}" master:master 
branches:
    only:
        - hexo 
env:
    global:
        - GH_REF: github.com/ingjieye/ingjieye.github.io.git #设置GH_REF，注意更改yourname
